# Generated by Django 5.2.15 on 2026-06-27 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_studentexam_proctor_last_frame_at'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='banappeal',
            new_name='ban_appeals_student_d8dc1e_idx',
            old_name='ban_appeals_student_4c2869_idx',
        ),
        migrations.RenameIndex(
            model_name='banappeal',
            new_name='ban_appeals_status_e3f5a9_idx',
            old_name='ban_appeals_status_4ec8b1_idx',
        ),
        migrations.RenameIndex(
            model_name='banappealevent',
            new_name='ban_appeal__appeal__9767ee_idx',
            old_name='ban_appeal_appeal__7ee220_idx',
        ),
    ]
