# Generated by Django 5.2.15 on 2026-07-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_audit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexam',
            name='identity_last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='identity_last_code',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='identity_last_matched',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='identity_last_method',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AddField(
            model_name='studentexam',
            name='identity_last_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
