# Generated by Django 5.2.15 on 2026-07-31 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auditlog_bigint_pk'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='ambient_audio_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
