# Generated by Django 5.2.15 on 2026-08-02 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_exam_ambient_audio_toggle'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='intake_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
