# Generated by Django 5.2.15 on 2026-08-02 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_add_group_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kafedra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'kafedralar',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='direction',
            name='kafedra',
            field=models.ForeignKey(blank=True, db_column='kafedra_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='directions', to='core.kafedra'),
        ),
    ]
