# Generated by Django 5.2.15 on 2026-08-02 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_add_kafedra'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='direction',
            field=models.ForeignKey(blank=True, db_column='direction_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.direction'),
        ),
    ]
