from django.urls import path

from apps.api import views

urlpatterns = [
    path("internal/realtime/exam-access", views.internal_realtime_exam_access),
    path("public/academic-catalog/", views.public_academic_catalog),
    path("health", views.health),
    path("live", views.health_live),
    path("ready", views.health_ready),
    path("auth/login", views.auth_login),
    path("auth/me", views.auth_me),
    path("student/identity-compare", views.student_identity_compare),
    path("student/exams", views.student_exams_list),
    path("student/exams/<int:pk>/clock", views.student_exam_clock),
    path("student/exams/<int:pk>/draft", views.student_exam_draft),
    path("student/exams/<int:pk>/save-progress", views.student_exam_save_progress),
    path("student/exams/<int:pk>/start", views.student_exams_start),
    path("student/proctor-config", views.student_proctor_config),
    path("student/exams/<int:pk>/submit", views.student_exams_submit),
    path("student/results", views.student_results),
    path("student/exams/<int:exam_id>/result-details", views.student_result_details),
    path("student/exams/<int:exam_id>/certificate.pdf", views.student_certificate_pdf),
    path("student/ban-report.pdf", views.student_ban_report_pdf),
    path("student/ban-appeals", views.student_ban_appeals),
    path("student/violations", views.student_violations),
    path("student/exams/<int:pk>/proctor-frame", views.student_proctor_frame),
    path(
        "student/exams/<int:pk>/proctor-frame/<str:task_id>",
        views.student_proctor_frame_result,
    ),
    path("staff/exams", views.staff_exams_list),
    path("staff/exams/<int:pk>/results", views.staff_exams_results),
    path("admin/review-queue", views.admin_review_queue),
    path("admin/users", views.admin_users),
    path("admin/users/<str:user_id>/unban", views.admin_users_unban),
    path("admin/users/<str:user_id>", views.admin_user_detail),
    path("admin/ban-appeals", views.admin_ban_appeals),
    path("admin/ban-appeals/<int:pk>/events", views.admin_ban_appeal_events),
    path("admin/ban-appeals/<int:pk>/resolve", views.admin_ban_appeal_resolve),
    path("admin/student_exams/<int:pk>/retake", views.admin_student_exams_retake),
    path("admin/student_exams/<int:pk>/unblock", views.admin_student_exams_unblock),
    path("admin/student_exams/<int:pk>/grant-technical-retakes", views.admin_student_exams_grant_technical_retakes),
    path("admin/student_exams/<int:pk>/fail", views.admin_student_exams_fail),
    path("admin/stats", views.admin_stats),
    path("admin/audit-log", views.admin_audit_log),
    path("admin/levels", views.admin_levels),
    path("admin/levels/<int:pk>", views.admin_level_detail),
    path("admin/kafedralar", views.admin_kafedralar),
    path("admin/kafedralar/<int:pk>", views.admin_kafedra_detail),
    path("admin/directions", views.admin_directions),
    path("admin/directions/<int:pk>", views.admin_direction_detail),
    path("admin/groups", views.admin_groups),
    path("admin/groups/<int:pk>", views.admin_group_detail),
    path("admin/test-bank/categories", views.admin_test_bank_categories),
    path("admin/test-bank/categories/<int:pk>", views.admin_test_bank_categories_delete),
    path("admin/test-bank/import-smart", views.admin_test_bank_import_smart),
    path("admin/test-bank/questions", views.admin_test_bank_questions),
    path("admin/imentor/departments", views.admin_imentor_departments),
    path("admin/imentor/departments/<str:department_code>/subjects", views.admin_imentor_department_subjects),
    path("admin/imentor/subjects", views.admin_imentor_subjects),
    path("admin/exams", views.admin_exams),
    path("admin/exams/<int:pk>/results", views.admin_exams_results),
    path("admin/exams/<int:pk>/exceptions", views.admin_exam_exceptions),
    path("admin/exams/<int:pk>/retake-windows", views.admin_exam_retake_windows),
    path(
        "admin/exams/<int:pk>/retake-windows/<int:wid>",
        views.admin_exam_retake_window_delete,
    ),
    path("admin/exams/<int:pk>", views.admin_exam_detail),
    path(
        "public/verify-result/<str:result_id>/certificate.pdf",
        views.public_verify_certificate_pdf,
    ),
    path("public/verify-result/<str:result_id>", views.public_verify_result),
    path("public/verify-ban-report", views.public_verify_ban_report),
]
